spring.application.name=issuetracker
spring.datasource.url=jdbc:postgresql://localhost:5432/issuetracker
spring.datasource.username=user
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

security.jwt.secret=${JWT_SECRET}
security.jwt.expiration-ms=3600000