spring.application.name=issuetracker
spring.datasource.url=jdbc:postgresql://localhost:5432/issuetracker
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true